name: NoMask

logger:
  path: "logs"
  verbosity: 2

train_dataloader:
  name: MaskPairImageDataLoader
  args:
    masked_image_dir: './data/processed/masked_image'
    identity_image_dir: './data/processed/identity_image'
    unmasked_image_dir: './data/processed/unmasked_image'
    batch_size: 2
    shuffle: True,
    num_workers: 2

validation_dataloader:
  name: MaskPairImageDataLoader
  args:
    masked_image_dir: './data/processed/masked_image'
    identity_image_dir: './data/processed/identity_image'
    unmasked_image_dir: './data/processed/unmasked_image'
    batch_size: 2 
    shuffle: True,
    num_workers: 2

model:
  name: MaskRemover 
  args:
    output_resolution: 512
    latent_dim: 512

loss:
  name: MaskRemoverLoss
  args:
    lambda_content: 0.1
    lambda_perceptual: 0.5
    lambda_identity: 0.4

optimizer:
  name: Adam
  args:
    lr: 0.004

lr_scheduler:
  name: "CosineAnnealingWarmRestarts"
  args:
    T_0: 25
    T_mult: 1
    eta_min: 0.00005

trainer:
  num_epochs: 100
  log_step: 100

  checkpoint_dir: "experiments/"
  save_period: 1

  monitor: "min_val_loss"
  early_stop: 10

  use_tensorboard: True

  validation:
    do_validation: True
    validation_steps: 5

