name: UnVeilify
deterministic: True
seed: 10

logger:
  path: "logs"
  verbosity: 2

train_dataloader:
  name: MaskPairImageDataLoader
  args:
    masked_image_dir: './data/processed/masked_image/train'
    identity_image_dir: './data/processed/identity_image/train'
    unmasked_image_dir: './data/processed/unmasked_image/train'
    batch_size: 2
    shuffle: True,
    num_workers: 2
    image_resolution: 256

validation_dataloader:
  name: MaskPairImageDataLoader
  args:
    masked_image_dir: './data/processed/masked_image/val'
    identity_image_dir: './data/processed/identity_image/val'
    unmasked_image_dir: './data/processed/unmasked_image/val'
    batch_size: 2 
    shuffle: True,
    num_workers: 2
    image_resolution: 256

model:
  generator:
    name: MaskRemover 
    args:
      output_resolution: 256
      latent_dim: 512
      generator_arch: UNetStyleGAN
  discriminator:
    name: Discriminator

loss:
  name: MaskRemoverLoss
  args:
    pretrained_irse50: './pretrain/irse_50.pth'
    lambda_content: 1.0
    lambda_perceptual: 5.0
    lambda_identity: 0.5
    lambda_adversarial: 1.0

optimizer:
  optim_g:
    name: Adam
    args:
      lr: !!float 3e-4
      eps: !!float 1e-8
      betas: [0.9, 0.99]

  optim_d:
    name: Adam
    args:
      lr: !!float 3e-4
      eps: !!float 1e-8
      betas: [0.9, 0.99]

lr_scheduler:
  name: MultiStepLR
  args:
    milestones: [2500, 5000, 10000, 20000]
    gamma: 0.5

trainer:
  num_epochs: 100
  log_step: 5

  checkpoint_dir: "experiments/"
  save_period: 1

  monitor: "min_val_loss"
  early_stop: 10

  use_tensorboard: True
  visualization: True

  validation:
    do_validation: True
    validation_steps: 5

